version: '3.9'
networks:
  traefik:
    external: true
services:
  nginx:
    image: africa.nginx:latest
    container_name: africa.nginx
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    networks:
      - traefik
      - default
    volumes:
      - ./app:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sales.rule=Host(`african-days.ru`)"
      - "traefik.http.routers.sales.entryPoints=http"
      - "traefik.http.services.sales.loadBalancer.server.port=80"
      - "traefik.http.routers.sales.middlewares=redirectToHttps"
      - "traefik.http.middlewares.redirectToHttps.redirectScheme.scheme=https"
      - "traefik.http.middlewares.redirectToHttps.redirectScheme.permanent=true"
      - "traefik.http.routers.sslSales.rule=Host(`african-days.ru`)"
      - "traefik.http.routers.sslSales.entryPoints=https"
      - "traefik.http.routers.sslSales.tls=true"
      - "traefik.http.routers.sslSales.tls.certResolver=letsEncrypt"

  node:
    image: africa.node:latest
    build:
      context: .
      dockerfile: .docker/node/Dockerfile
    container_name: africa.node
    command: [ "/usr/local/bin/sass", "--watch", "/app/resources/css/main.scss", "/app/public/style/main.css" ]
    volumes:
      - ./app:/app:delegated